### PR TITLE
Changes LICENSE to DoNoHarm Apache2

### PR DESCRIPTION
**Pull request by jasongwartz**

### CODE REVIEW

**Comment by LostCrew** [comment]
- Are we obliged to perform extra procedures to switch from current to new license? I ask because it's the case with other license migrations
- Don't forget to update package.json's [licence](https://github.com/ecosia/eslint-config/blob/master/package.json#L16) field too

**Comment by jasongwartz** [comment]
@LostCrew 

1: Dunno, IANAL
2. Didn't think of that, cheers

**Comment by LostCrew** [comment]
@jasongwartz For the sake of safety, let's gather approval from all contributors so far. I hereby give mine. @Globegitter ?

**Comment by Globegitter** [comment]
It might be worth to update to their latest version: https://github.com/raisely/NoHarm/commit/a306ad46c89a5d4694f25eb8ca2f54a5d285171e but otherwise :+1:

**Comment by jasongwartz** [comment]
@LostCrew let me know when you can take another look

**Pull request merged**
